module.exports={
    data:[
        {
            TB_NAME:"baseInfo",
            DB_NAME:"DB1",
            parentNode:"root",//父节点
            searchNode:"title",//搜索的节点
            fields:[{
                 type:"rename", //分三种，rename add ignore
                 xpath:'//root/title/h1',//路径
                 columnName:"title" //重命名
              }
           ],
            clone:"1" //是否克隆，1为克隆，0 为不克隆
        },
        {
            TB_NAME:"items",
            DB_NAME:"DB1",
            parentNode:"items",
            searchNode:"item",
            fields:[
                 {
                    type:"add",
                    xpath:"//root/title/claim_no",
                    columnName:""
                  },
                  {
                    type:"ignore",
                    fieldName:"b1"//忽略的字段
                  }
            ],
            clone:"1"
        },
        {
            TB_NAME:"sub_item",
            DB_NAME:"DB1",
            parentNode:"item",
            searchNode:"sub_item",
            fields:[
                 {
                    type:"add",
                    xpath:"//root/title/claim_no",
                    columnName:""
                  },
                  {
                    type:"add",
                    xpath:"../fid",
                    columnName:""
                  },
            ],
            clone:"1"
        },

    ]
}