module.exports={
    data:[
        {
            TB_NAME:"baseInfo",
            DB_NAME:"DB1",
            parentNode:"root",
            search_Node:"title",
            fields:[{
                 type:"rename",
                 xpath:'//root/title/h1',
                 columnName:"title"
             }
           ],
            clone:"1"
        },
        {
            TB_NAME:"items",
             DB_NAME:"DB1",
            parentNode:"items",
            search_Node:"item",
            fields:[
                {
                    type:"add",
                    xpath:"//root/title/claim_no",
                    columnName:""
                  },
            ],
            clone:"1"
        },
        {
            TB_NAME:"sub_item",
            DB_NAME:"DB1",
            parentNode:"item",
            search_Node:"sub_item",
            fields:[
                 {
                    type:"add",
                    xpath:"//root/title/claim_no",
                    columnName:""
                  },
                  {
                    type:"add",
                    xpath:"../fid",
                    columnName:""
                  },
            ],
            clone:"1"
        },

    ]
}